---
- hosts: webservers
  become: yes
  tasks:
    - name: groupadd "sroot"
      group:
        name: sroot
        state: present
    - name: useradd "sroot"
      user:
        name: sroot
        group: mpl
    - name: yum install nginx
      yum:
        name: nginx
        state: present
    - name : Copy nginx.conf
      copy:
        src: /etc/ansible/roles/web/files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
    - name : systemctl start nginx
      service:
        name: nginx
        state: started