---
- hosts:  targets
  become: yes
  tasks:
    - name: output msgs
      debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
    - name: double quote, double kakko
      debug:
        msg: "{{ ansible_nodename }}" # varだと半角空白が無いとエラーになる
    - name: no quote, no kakko
      debug:
        msg: ansible_os_family # これも変数扱いになる
    
    # SMARTS用セットアップ
    - name: Ensure group "mpl" exists
      group:
        name: mpl
        state: present
    - name: Add the user 'sroot' with a specific uid and a primary group of 'admin'
      user:
        name: sroot
        group: mpl # primary group
    - name: Create a 2048-bit SSH key for user sroot in ~sroot/.ssh/id_rsa
      user:
        name: sroot
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa