---
- hosts: webservers
  become: yes
  vars:
    msg: "Hello, world"
    ip_addr: 192.168.0.1
    pkgs:
      - nginx
      - git
  tasks:
    - name: groupadd "sroot"
      group:
        name: sroot
        state: present
    - name: useradd "sroot"
      user:
        name: sroot
        group: mpl
    - name: install pkgs
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ pkgs }}"
    - name : Copy nginx.conf
      copy:
        src: /etc/ansible/roles/web/files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
    - name : systemctl start nginx
      service:
        name: nginx
        state: started
    - name: set Timezone as Asia/Tokyo
      timezone:
        name: Asia/Tokyo
    - name: set locale as LANG=ja_JP.utf8
      command: localectl set-locale LANG=ja_JP.utf8