---
- hosts: testgroup1
  become: yes
  tasks:
  - name: CREATE A NEW GROUP
    group:
      name: testgroup1
      state: present
  - name: CREATE A NEW USER
    user:
      name: testuser1
      group: testgroup1

  - name: TIMEZONE SETTING
    timezone:
      name: Asia/Tokyo
  - name: LOCALE SETTING
    command: localectl set-locale LANG=ja_JP.utf8

  - name: NEW USELESS FILE
    file:
      path: /tmp/useless.file
      owner: testuser1
      group: testgroup1
      mode: '744'
      state: touch
  - name: REMOVE USELESS FILE
    file:
      path: /tmp/useless.file
      state: absent

  - name: COPY FILE
    copy:
      src: ~/ansible/roles/common/files/copy_src.file
      dest: /tmp/copy_src.file
      mode: preserve

  - name: SET HOSTNAME
    hostname:
      name: testhost1

  - name: SET IPTABLES (BLOCK SPECICIC IP)
    iptables:
      chain: INPUT
      source: 8.8.8.8
      jump: DROP

  - name: DEBUG VAR
    debug:
      msg: "{{ yum_install }}"
