---
- hosts: testgroup1
  become: yes
  tasks:
  - name: CREATE A NEW GROUP
    group:
      name: testgroup1
      state: present
  - name: CREATE A NEW USER
    user:
      name: testuser1
      group: testgroup1
  - name: TIMEZONE SETTING
    timezone:
      name: Asia/Tokyo
  - name: LOCALE SETTING
    command: localectl set-locale LANG=ja_JP.utf8
