---
- name: CREATE A NEW GROUP
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    gid: "{{ item.gid }}"
  loop: "{{ my_groups }}"
- name: CREATE A NEW USER
  user:
    name: "{{ item.user }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.secondary_group }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.login_shell }}"
    create_home: "{{ item.create_home }}"
    password: "{{ item.password | password_hash('sha512','mysalt') }}"
  loop: "{{ my_users }}"

- name: TIMEZONE SETTING
  timezone:
    name: Asia/Tokyo
- name: LOCALE SETTING
  command: localectl set-locale LANG=ja_JP.utf8

- name: NEW USELESS FILE
  file:
    path: /tmp/useless.file
    owner: testuser1
    group: testgroup1
    mode: '744'
    state: touch
- name: REMOVE USELESS FILE
  file:
    path: /tmp/useless.file
    state: absent

- name: COPY FILE
  copy:
    src:  "{{ item.src_local }}"
    dest: "{{ item.dst_remote }}"
    mode: preserve
  loop: "{{ copy_files }}"

- name: SET HOSTNAME
  hostname:
    name: testhost1

- name: SET IPTABLES (BLOCK SPECICIC IP)
  iptables:
    chain: INPUT
    source: 8.8.8.8
    jump: DROP

- name: DEBUG VAR
  debug:
    msg: "{{ yum_install }}"

- name: CHECK SELINUX STATUS
  shell: getenforce
  register: selinux_state
- name: TURN OFF SELINUX (WHEN SELINUX NOT DISABLED)
  shell: setenforce 0
  when: selinux_state.stdout == "Enforcing"
- name: DISABLE SELINUX ON BOOT
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=disabled'

- name: SET SUDOERS
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^root +ALL=\(ALL\) +ALL$'
    line: 'root ALL=(ALL) ALL'